# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b523bbc4276e7fedb24c4868bf72c81b0b8dfa770cf2079d364280aa9583b38ba85403f6007ac2fa8aeead5b416c571783aca704bcaeb350197d45aa016d351

test:
  secret_key_base: 5163443f5620c7d1126f8844ac25bbcb7e7a09763d6d5df8d70d3c72fb7c3867f9b1eca7461c056594a04893601556b766a373ba9f32b97223b4a86cc5087382

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
